In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier

## Train

geo level sum

In [2]:
train = pd.read_csv('../Train/train_set_geo_level_sum.csv')

train.head()

,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,...,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,count_families,geo_level_1_id_sum,geo_level_2_id_sum,geo_level_3_id_sum,damage_grade
0,6,487,12198,2,30,6,5,1,1,0,...,0,0,0,0,0,1,24381,270,37,3
1,8,900,2812,2,10,8,7,0,1,0,...,0,0,0,0,0,1,19080,199,16,2
2,21,363,8973,2,10,5,5,0,1,0,...,0,0,0,0,0,1,14889,1760,136,3
3,22,418,10694,2,10,6,5,0,1,0,...,1,1,0,0,0,1,6252,205,31,2
4,11,131,1488,3,30,8,9,1,0,0,...,0,0,0,0,0,1,8220,1038,122,3

In [4]:
X, y = train.iloc[:,:-1], train.iloc[:,-1]

In [6]:
rf_model = RandomForestClassifier(n_estimators=15, max_depth=3, max_features='log2', random_state=123)
rf_model.fit(X, y)

RandomForestClassifier(max_depth=3, max_features='log2', n_estimators=15,
                       random_state=123)

In [7]:
leaf_index = rf_model.apply(X)

leaf_index

array([[ 3,  3,  3, ..., 11,  4,  3],
       [ 3,  3,  6, ...,  7, 10, 10],
       [ 6,  3,  6, ...,  6, 10, 10],
       ...,
       [ 7,  3,  6, ...,  7, 11, 10],
       [11, 14, 13, ..., 14, 13, 14],
       [ 6,  3,  6, ...,  7, 11, 10]])

In [8]:
leaf_index_df = pd.DataFrame(leaf_index)

leaf_index_df

        0   1   2   3   4   5   6   7   8   9   10  11  12  13  14
0        3   3   3   7   6  10  11   4   6  13  14   4  11   4   3
1        3   3   6   7   6  13  11   4  10   6  14   4   7  10  10
2        6   3   6   7   6  13  11   4  10   4  14   4   6  10  10
3       10  10   6   7   6  14  11   4  11   4  14   4   6  10  11
4        3   3   6   6   4  13  10   6  10   3  13   4   7  11  10
...     ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
260596  13  10   6   7   6   4   4   4  10   4  14   3   6  10  11
260597   7   3   6   4   6  13  11   4  10   6   4   4   3  10  10
260598   7   3   6   7   6  13  11   7  10   6  14   4   7  11  10
260599  11  14  13  11  14  14  10  11  13  11  13  14  14  13  14
260600   6   3   6   7   6  13  11   7  10   4  14   4   7  11  10

[260601 rows x 15 columns]

In [9]:
cols = list(leaf_index_df.columns)

new_cols = ["leaf_index_"+str(n) for n in cols]

new_cols

['leaf_index_0',
 'leaf_index_1',
 'leaf_index_2',
 'leaf_index_3',
 'leaf_index_4',
 'leaf_index_5',
 'leaf_index_6',
 'leaf_index_7',
 'leaf_index_8',
 'leaf_index_9',
 'leaf_index_10',
 'leaf_index_11',
 'leaf_index_12',
 'leaf_index_13',
 'leaf_index_14']

In [10]:
leaf_index_df.columns = new_cols

leaf_index_df

,leaf_index_0,leaf_index_1,leaf_index_2,leaf_index_3,leaf_index_4,leaf_index_5,leaf_index_6,leaf_index_7,leaf_index_8,leaf_index_9,leaf_index_10,leaf_index_11,leaf_index_12,leaf_index_13,leaf_index_14
0,3,3,3,7,6,10,11,4,6,13,14,4,11,4,3
1,3,3,6,7,6,13,11,4,10,6,14,4,7,10,10
2,6,3,6,7,6,13,11,4,10,4,14,4,6,10,10
3,10,10,6,7,6,14,11,4,11,4,14,4,6,10,11
4,3,3,6,6,4,13,10,6,10,3,13,4,7,11,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260596,13,10,6,7,6,4,4,4,10,4,14,3,6,10,11
260597,7,3,6,4,6,13,11,4,10,6,4,4,3,10,10
260598,7,3,6,7,6,13,11,7,10,6,14,4,7,11,10
260599,11,14,13,11,14,14,10,11,13,11,13,14,14,13,14
260600,6,3,6,7,6,13,11,7,10,4,14,4,7,11,10

In [11]:
result = train.join(leaf_index_df)

result

,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,...,leaf_index_5,leaf_index_6,leaf_index_7,leaf_index_8,leaf_index_9,leaf_index_10,leaf_index_11,leaf_index_12,leaf_index_13,leaf_index_14
0,6,487,12198,2,30,6,5,1,1,0,...,10,11,4,6,13,14,4,11,4,3
1,8,900,2812,2,10,8,7,0,1,0,...,13,11,4,10,6,14,4,7,10,10
2,21,363,8973,2,10,5,5,0,1,0,...,13,11,4,10,4,14,4,6,10,10
3,22,418,10694,2,10,6,5,0,1,0,...,14,11,4,11,4,14,4,6,10,11
4,11,131,1488,3,30,8,9,1,0,0,...,13,10,6,10,3,13,4,7,11,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260596,25,1335,1621,1,55,6,3,0,1,0,...,4,4,4,10,4,14,3,6,10,11
260597,17,715,2060,2,0,6,5,0,1,0,...,13,11,4,10,6,4,4,3,10,10
260598,17,51,8163,3,55,6,7,0,1,0,...,13,11,7,10,6,14,4,7,11,10
260599,26,39,1851,2,10,14,6,0,0,0,...,14,10,11,13,11,13,14,14,13,14
260600,21,9,9101,3,10,7,6,0,1,0,...,13,11,7,10,4,14,4,7,11,10

In [12]:
cols = list(result.columns)
cols.remove('damage_grade')
cols.append('damage_grade')

result = result[cols]

result

,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,...,leaf_index_6,leaf_index_7,leaf_index_8,leaf_index_9,leaf_index_10,leaf_index_11,leaf_index_12,leaf_index_13,leaf_index_14,damage_grade
0,6,487,12198,2,30,6,5,1,1,0,...,11,4,6,13,14,4,11,4,3,3
1,8,900,2812,2,10,8,7,0,1,0,...,11,4,10,6,14,4,7,10,10,2
2,21,363,8973,2,10,5,5,0,1,0,...,11,4,10,4,14,4,6,10,10,3
3,22,418,10694,2,10,6,5,0,1,0,...,11,4,11,4,14,4,6,10,11,2
4,11,131,1488,3,30,8,9,1,0,0,...,10,6,10,3,13,4,7,11,10,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260596,25,1335,1621,1,55,6,3,0,1,0,...,4,4,10,4,14,3,6,10,11,2
260597,17,715,2060,2,0,6,5,0,1,0,...,11,4,10,6,4,4,3,10,10,3
260598,17,51,8163,3,55,6,7,0,1,0,...,11,7,10,6,14,4,7,11,10,3
260599,26,39,1851,2,10,14,6,0,0,0,...,10,11,13,11,13,14,14,13,14,2
260600,21,9,9101,3,10,7,6,0,1,0,...,11,7,10,4,14,4,7,11,10,3

In [13]:
result.to_csv('../Train/train_set_geo_sum_base_rf_leaf_index.csv', index=False)

One hot encoding

In [14]:
train = pd.read_csv('../Train/train_set_one_hot_encoding.csv')

train.head()

,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,...,plan_configuration_a,plan_configuration_o,plan_configuration_m,plan_configuration_n,plan_configuration_f,legal_ownership_status_v,legal_ownership_status_a,legal_ownership_status_w,legal_ownership_status_r,damage_grade
0,6,487,12198,2,30,6,5,1,1,0,...,0,0,0,0,0,1,0,0,0,3
1,8,900,2812,2,10,8,7,0,1,0,...,0,0,0,0,0,1,0,0,0,2
2,21,363,8973,2,10,5,5,0,1,0,...,0,0,0,0,0,1,0,0,0,3
3,22,418,10694,2,10,6,5,0,1,0,...,0,0,0,0,0,1,0,0,0,2
4,11,131,1488,3,30,8,9,1,0,0,...,0,0,0,0,0,1,0,0,0,3

In [15]:
X, y = train.iloc[:,:-1], train.iloc[:,-1]

In [16]:
rf_model = RandomForestClassifier(n_estimators=35, max_depth=3, max_features='log2', random_state=123)
rf_model.fit(X, y)

RandomForestClassifier(max_depth=3, max_features='log2', n_estimators=35,
                       random_state=123)

In [17]:
leaf_index = rf_model.apply(X)

leaf_index

array([[ 3,  7,  4, ...,  3, 10, 11],
       [ 7,  6,  6, ...,  6, 13, 10],
       [ 7,  7,  6, ...,  3, 10, 11],
       ...,
       [ 7,  7,  6, ...,  7, 13, 13],
       [10,  7,  7, ..., 11, 14, 10],
       [ 7,  6,  6, ...,  3, 13, 13]])

In [18]:
leaf_index_df = pd.DataFrame(leaf_index)

leaf_index_df

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,3,7,4,7,10,10,3,6,7,3,...,3,4,11,3,11,11,6,3,10,11
1,7,6,6,6,10,11,6,7,4,3,...,3,6,11,3,11,6,10,6,13,10
2,7,7,6,7,10,10,6,6,7,3,...,3,6,11,3,11,11,10,3,10,11
3,7,7,6,13,10,10,6,7,6,3,...,3,7,11,3,11,11,11,7,11,10
4,7,7,6,7,10,11,6,3,6,3,...,3,6,13,3,10,10,10,7,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260596,7,3,6,7,3,6,13,7,6,3,...,4,7,11,3,6,11,11,7,11,10
260597,7,7,6,7,10,10,6,7,6,3,...,3,6,10,3,11,11,10,7,10,10
260598,7,7,6,7,10,10,6,7,6,3,...,3,6,14,3,11,11,10,7,13,13
260599,10,7,7,6,13,14,7,3,3,3,...,3,10,11,6,14,3,11,11,14,10
260600,7,6,6,7,10,11,6,6,6,3,...,3,6,14,3,11,11,10,3,13,13

In [19]:
cols = list(leaf_index_df.columns)

new_cols = ["leaf_index_"+str(n) for n in cols]

new_cols

['leaf_index_0',
 'leaf_index_1',
 'leaf_index_2',
 'leaf_index_3',
 'leaf_index_4',
 'leaf_index_5',
 'leaf_index_6',
 'leaf_index_7',
 'leaf_index_8',
 'leaf_index_9',
 'leaf_index_10',
 'leaf_index_11',
 'leaf_index_12',
 'leaf_index_13',
 'leaf_index_14',
 'leaf_index_15',
 'leaf_index_16',
 'leaf_index_17',
 'leaf_index_18',
 'leaf_index_19',
 'leaf_index_20',
 'leaf_index_21',
 'leaf_index_22',
 'leaf_index_23',
 'leaf_index_24',
 'leaf_index_25',
 'leaf_index_26',
 'leaf_index_27',
 'leaf_index_28',
 'leaf_index_29',
 'leaf_index_30',
 'leaf_index_31',
 'leaf_index_32',
 'leaf_index_33',
 'leaf_index_34']

In [20]:
leaf_index_df.columns = new_cols

leaf_index_df

,leaf_index_0,leaf_index_1,leaf_index_2,leaf_index_3,leaf_index_4,leaf_index_5,leaf_index_6,leaf_index_7,leaf_index_8,leaf_index_9,...,leaf_index_25,leaf_index_26,leaf_index_27,leaf_index_28,leaf_index_29,leaf_index_30,leaf_index_31,leaf_index_32,leaf_index_33,leaf_index_34
0,3,7,4,7,10,10,3,6,7,3,...,3,4,11,3,11,11,6,3,10,11
1,7,6,6,6,10,11,6,7,4,3,...,3,6,11,3,11,6,10,6,13,10
2,7,7,6,7,10,10,6,6,7,3,...,3,6,11,3,11,11,10,3,10,11
3,7,7,6,13,10,10,6,7,6,3,...,3,7,11,3,11,11,11,7,11,10
4,7,7,6,7,10,11,6,3,6,3,...,3,6,13,3,10,10,10,7,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260596,7,3,6,7,3,6,13,7,6,3,...,4,7,11,3,6,11,11,7,11,10
260597,7,7,6,7,10,10,6,7,6,3,...,3,6,10,3,11,11,10,7,10,10
260598,7,7,6,7,10,10,6,7,6,3,...,3,6,14,3,11,11,10,7,13,13
260599,10,7,7,6,13,14,7,3,3,3,...,3,10,11,6,14,3,11,11,14,10
260600,7,6,6,7,10,11,6,6,6,3,...,3,6,14,3,11,11,10,3,13,13

In [21]:
result = train.join(leaf_index_df)

result

,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,...,leaf_index_25,leaf_index_26,leaf_index_27,leaf_index_28,leaf_index_29,leaf_index_30,leaf_index_31,leaf_index_32,leaf_index_33,leaf_index_34
0,6,487,12198,2,30,6,5,1,1,0,...,3,4,11,3,11,11,6,3,10,11
1,8,900,2812,2,10,8,7,0,1,0,...,3,6,11,3,11,6,10,6,13,10
2,21,363,8973,2,10,5,5,0,1,0,...,3,6,11,3,11,11,10,3,10,11
3,22,418,10694,2,10,6,5,0,1,0,...,3,7,11,3,11,11,11,7,11,10
4,11,131,1488,3,30,8,9,1,0,0,...,3,6,13,3,10,10,10,7,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260596,25,1335,1621,1,55,6,3,0,1,0,...,4,7,11,3,6,11,11,7,11,10
260597,17,715,2060,2,0,6,5,0,1,0,...,3,6,10,3,11,11,10,7,10,10
260598,17,51,8163,3,55,6,7,0,1,0,...,3,6,14,3,11,11,10,7,13,13
260599,26,39,1851,2,10,14,6,0,0,0,...,3,10,11,6,14,3,11,11,14,10
260600,21,9,9101,3,10,7,6,0,1,0,...,3,6,14,3,11,11,10,3,13,13

In [22]:
cols = list(result.columns)
cols.remove('damage_grade')
cols.append('damage_grade')

result = result[cols]

result

,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,...,leaf_index_26,leaf_index_27,leaf_index_28,leaf_index_29,leaf_index_30,leaf_index_31,leaf_index_32,leaf_index_33,leaf_index_34,damage_grade
0,6,487,12198,2,30,6,5,1,1,0,...,4,11,3,11,11,6,3,10,11,3
1,8,900,2812,2,10,8,7,0,1,0,...,6,11,3,11,6,10,6,13,10,2
2,21,363,8973,2,10,5,5,0,1,0,...,6,11,3,11,11,10,3,10,11,3
3,22,418,10694,2,10,6,5,0,1,0,...,7,11,3,11,11,11,7,11,10,2
4,11,131,1488,3,30,8,9,1,0,0,...,6,13,3,10,10,10,7,13,13,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260596,25,1335,1621,1,55,6,3,0,1,0,...,7,11,3,6,11,11,7,11,10,2
260597,17,715,2060,2,0,6,5,0,1,0,...,6,10,3,11,11,10,7,10,10,3
260598,17,51,8163,3,55,6,7,0,1,0,...,6,14,3,11,11,10,7,13,13,3
260599,26,39,1851,2,10,14,6,0,0,0,...,10,11,6,14,3,11,11,14,10,2
260600,21,9,9101,3,10,7,6,0,1,0,...,6,14,3,11,11,10,3,13,13,3

In [23]:
result.to_csv('../Train/train_set_one_hot_rf_leaf_index.csv', index=False)